### ISSUE TITLE
[BUG] Type of expiresAt is string instead Date

### ISSUE THREAD

**Issue by tobias-jueschke** [Adyen/adyen-node-api-library#957] opened 2022-08-11 12:00 UTC
**Describe the bug**
Creating a session request with the client `CheckoutAPI.sessions(...)` result in a `CreateCheckoutSessionResponse` object. Checking the Type of the property `expiresAt`, should be a Date but is string.

**To Reproduce**
Create session request via `CheckoutAPI.sessions(...)`  check the type of result.expiresAt. 

**Expected behavior**
If the type of expiresAt is Date it should be deserialized to Date not string.

**Desktop (please complete the following information):**
 - OS: Alpine
 - Node Version: 16.14.0
 - NPM Version: 8.3.1

**Comment by jillingk** [comment] 2022-08-11 12:04
Hey @tobias-jueschke,

Thank you for reaching out to us with this issue. What library version are you currently using? We had this issue in the past but have since fixed this in a newer version. Keep me posted!

Best, Jilling
Adyen

**Comment by michaelpaul** [comment] 2022-08-11 12:21
Duplicate of #887

**Comment by tobias-jueschke** [comment] 2022-08-11 12:27
Thank you for answering, is there a time scheduled for the release?

**Comment by jillingk** [comment] 2022-08-12 11:30
Hey @tobias-jueschke,

We are still finalising some newly added endpoints, but we're aiming to release it very soon with as ultimatum three weeks from now. Hope this works with your schedule!

Best, Jilling
Adyen

**Closed by jillingk** 2022-08-12 11:30 UTC
Labels: bug, duplicate
