### ISSUE TITLE
Typing issue

### ISSUE THREAD

**Issue by dthib** [Adyen/adyen-node-api-library#754] opened 2021-09-09 07:48 UTC
Dear Adyen Team,

In addition to https://github.com/Adyen/adyen-node-api-library/issues/740, there are other typescript issues in particular for enum which prevents from using correctly the library.

Describe the bug
In typepescript, enum are considered by default numeric if the value are not specifid (see https://www.typescriptlang.org/docs/handbook/enums.html). 
In the api library, the value are not specified so the enum are considered numeric whereas the API returns string values.
We are forced to use forced conversion (see sceenshot)

To Reproduce
With the latest version @adyen/api-library:9.0.0

Expected behavior

Enum with specified string values or union types (see https://blog.bam.tech/developer-news/should-you-use-enums-or-union-types-in-typescript)

Screenshots

![image](https://user-images.githubusercontent.com/6855743/132643725-48d689f9-21a5-464e-ba31-00b549130397.png)

![image](https://user-images.githubusercontent.com/6855743/132643816-0719ae22-6df1-4cff-972b-30dceb7cf173.png)

Desktop (please complete the following information):

OS: MacOS
Node Version: v14.15.4
NPM Version: 6.14.10

**Comment by wboereboom** [comment] 2021-09-09 08:00
Hi @dthib,

Thanks for raising this issue.
We rely on the openAPI generator in order to generate all API types based on the spec. Unfortunately this is the way it generates Enums.

Could you (in your example) declare eventCode as  an `NotificationRequestItem.EventCodeEnum` type? This would make it so you don't have to force any conversions?

You could then also do the comparison based on the enum types rather than the string literal.

N.B: We are planning on making it easier to access the types from the root of our library, we are aware of the fact it is now a bit cumbersome to retrieve them. 

Kind regards,
Wouter
Adyen

**Comment by dthib** [comment] 2021-09-09 08:10
Hi @wboereboom ,

unfortunately it's not possible. It's what I have been doing before and it was not working. If I write down this below (see screenshots), we are comparing a received string to a number so we are never entering the if....

![image](https://user-images.githubusercontent.com/6855743/132648528-9d114d19-3254-4dd1-ba90-18206845ef4d.png)

Best

**Comment by wboereboom** [comment] 2021-09-09 09:33
This story is a duplicate of #494. We do not want to update the models by hand in order to uphold the maintainability of the library types.
We'll be looking into some automated way to fix this.

**Closed** 2021-11-18 13:06 UTC
Labels: duplicate, feature, wontfix

**Comment by photz-insify** [comment] 2023-05-10 14:58
Interestingly the corresponding string values are present here:
https://github.com/Adyen/adyen-node-api-library/blob/develop/src/typings/notification/notificationRequestItem.ts#L149
